services:
  nginx:
    image: nginx:1.22
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/public
    ports:
      - "127.0.0.1:80:80/tcp"
    links:
      - app

  app:
    build: .
    environment:
      ISUCONP_DB_HOST: mysql
      ISUCONP_DB_PORT: 3306
      ISUCONP_DB_USER: root
      ISUCONP_DB_PASSWORD: root
      ISUCONP_DB_NAME: isuconp
      ISUCONP_MEMCACHED_ADDRESS: memcached:11211
      MOCK_ENDPOINT_URL: http://s3mock:9000
      AWS_ACCESS_KEY_ID: 'minio'
      AWS_SECRET_ACCESS_KEY: 'password'

    links:
      - mysql
      - memcached
    volumes:
      - ./public:/home/public
    init: true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g

  mysql:
    image: mysql/mysql-server:8.0
    environment:
      - "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - mysql:/var/lib/mysql
      - ./etc/my.cnf:/etc/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g

  memcached:
    image: memcached:1.6

  s3mock:
    image: minio/minio:RELEASE.2022-09-07T22-25-02Z
    ports:
      - "127.0.0.1:9000:9000/tcp"
      - "127.0.0.1:43007:43007/tcp"
    volumes:
      - s3_data:/export
    environment:
      - 'MINIO_ACCESS_KEY=minio'
      - 'MINIO_SECRET_KEY=password'
    command: "server /export --address :9000 --console-address :43007"
volumes:
  mysql:
  s3_data:
